### ISSUE TITLE
Valgrind warnings

### ISSUE THREAD

**Issue by nikic** [derickr/timelib#61] opened 2019-02-08 11:50 UTC
We get a bunch of valgrind warnings like this:

```
==5484== Conditional jump or move depends on uninitialised value(s)
==5484==    at 0x4E2FE0: do_adjust_timezone (tm2unixtime.c:467)
==5484==    by 0x4E3349: timelib_update_ts (tm2unixtime.c:511)
==5484==    by 0x46EE49: php_date_date_set (php_date.c:3592)
==5484==    by 0x46EF57: zif_date_date_set (php_date.c:3607)
==5484==    by 0x1228582: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:983)
==5484==    by 0x1228582: execute_ex (zend_vm_execute.h:61488)
==5484==    by 0x1250B8E: zend_execute (zend_vm_execute.h:67896)
==5484==    by 0xFA74BF: zend_execute_scripts (zend.c:1639)
==5484==    by 0xE94CE8: php_execute_script (main.c:2607)
==5484==    by 0x1256A7F: do_cli (php_cli.c:992)
==5484==    by 0x125853D: main (php_cli.c:1384)
```

For example http://gcov.php.net/viewer.php?version=PHP_HEAD&func=valgrind&file=ext%2Fdate%2Ftests%2FDateTime_add-massive.phpt.

The relevant line is here:

https://github.com/derickr/timelib/blob/8e4110ae7842535c926d31f0c6a03faf678047dc/tm2unixtime.c#L467

I'm not sure if this is a timelib issue, might also be a problem with how it's used in PHP.

**Comment by nikic** [comment] 2019-06-30 07:39
ping

**Comment by derickr** [comment] 2019-06-30 14:31
Duplicate of #65, which is fixed in master, but I'll backport for v2017.

**Closed by derickr** 2019-06-30 14:31 UTC
Labels: bug
